import platform, shutil

e = Environment()

BOOST_PATH="E:/Codes/lib/boost_1_57_0"
BOOST_BIN="E:/Codes/lib/boost_1_57_0/stage/lib"


if(platform.system() == "Linux"):
   e.Append( CPPFLAGS = '-Wall -pedantic -pthread -Wno-long-long' )
   e.Append( LINKFLAGS = '-Wall -pthread' )

   target = 'hello.so'

elif(platform.system() == "Windows"):
   e.Append( CPPFLAGS = ' /EHsc /D "WIN32" /D "_WIN32_WINNT#0x501" /D "_CONSOLE" /W4 /MD' )
   e.Append( CPPPATH = [ BOOST_PATH ] )
   e.Append( LIBPATH = [ BOOST_BIN ] )

else:
   print platform.system() + " not supported"

e.Program(target='server', source=['server/server.cpp', 'server/session.cpp', 'server/main.cpp'])