import platform, shutil

e = Environment()

BOOST_PATH="E:/Codes/lib/boost_1_57_0"
BOOST_BIN="E:/Codes/lib/boost_1_57_0/stage/lib"

e.Append( CPPPATH = '.' )

if(platform.system() == "Linux"):
   e.Append( CPPFLAGS = '-Wall -g -std=c++11 -pedantic -pthread -Wno-long-long' )
   e.Append( LINKFLAGS = '-Wall -pthread -lboost_system -lboost_thread' )

   target = 'hello.so'

elif(platform.system() == "Windows"):
   e.Append( CPPFLAGS = ' /EHsc /D "WIN32" /D "_WIN32_WINNT#0x501" /D "_CONSOLE" /W4 /MD' )
   e.Append( CPPPATH = [ BOOST_PATH ] )
   e.Append( LIBPATH = [ BOOST_BIN ] )

else:
   print platform.system() + " not supported"

e.Program(target='pokerd', source=['server/server.cpp',
			'server/session.cpp',
			'server/main.cpp',
			'server/lobby/lobby.cpp',
			'server/table/table.cpp',
			'common/requests/request_factory.cpp',
			'common/requests/msg.cpp',
			'common/requests/act.cpp',
			'common/requests/error.cpp',
			'common/requests/welcome.cpp',
			'common/requests/table_list.cpp',
			'common/requests/start.cpp',
			'common/requests/request.cpp',
			'common/requests/create_table.cpp',
			'common/requests/fetch.cpp',
			'common/requests/join.cpp',
			'common/requests/quit.cpp',
			'common/requests/cards.cpp',
			'jsoncpp.cpp',
			'common/requests/joined.cpp'])

e.Program(target='pokerc', source=['client/client.cpp',
			'client/main.cpp'])

e.Command(target='doc', source=['doxygen.conf'],
	action='doxygen doxygen.conf')
