import platform, shutil

e = Environment()

BOOST_PATH="E:/Codes/lib/boost_1_57_0"
BOOST_BIN="E:/Codes/lib/boost_1_57_0/stage/lib"

e.Append( CPPPATH = '.' )

if(platform.system() == "Linux"):
   e.Append( CPPFLAGS = '-Wall -g -pedantic -pthread -Wno-long-long -I/usr/include/jsoncpp' )
   e.Append( LINKFLAGS = '-Wall -pthread -lboost_system -ljsoncpp' )

   target = 'hello.so'

elif(platform.system() == "Windows"):
   e.Append( CPPFLAGS = ' /EHsc /D "WIN32" /D "_WIN32_WINNT#0x501" /D "_CONSOLE" /W4 /MD' )
   e.Append( CPPPATH = [ BOOST_PATH ] )
   e.Append( LIBPATH = [ BOOST_BIN ] )

else:
   print platform.system() + " not supported"

e.Program(target='pokerd', source=['server/server.cpp',
			'server/session.cpp',
			'server/main.cpp',
			'server/lobby/lobby.cpp',
			'common/requests/request_factory.cpp',
			'common/requests/msg.cpp',
			'common/requests/request.cpp',
			'common/requests/create_table.cpp'])
